# Generated by Django 5.2.6 on 2025-12-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_email_verified_profile_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp_created_at',
        ),
    ]
